"""add additional fields to models

Revision ID: 3e3431180c42
Revises: 619cced1d961
Create Date: 2024-03-15 22:33:02.438735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3431180c42'
down_revision: Union[str, None] = '619cced1d961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('type', sa.String(), nullable=False))
    op.add_column('animal', sa.Column('sex', sa.String(), nullable=False))
    op.add_column('animal', sa.Column('age', sa.String(), nullable=False))
    op.add_column('animal', sa.Column('size', sa.String(), nullable=False))
    op.create_unique_constraint(op.f('uq__animal__id'), 'animal', ['id'])
    op.drop_index('ix__photo__animal_id', table_name='animal_photo')
    op.drop_index('ix__photo__id', table_name='animal_photo')
    op.create_index(op.f('ix__animal_photo__animal_id'), 'animal_photo', ['animal_id'], unique=False)
    op.create_index(op.f('ix__animal_photo__id'), 'animal_photo', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__animal_photo__id'), table_name='animal_photo')
    op.drop_index(op.f('ix__animal_photo__animal_id'), table_name='animal_photo')
    op.create_index('ix__photo__id', 'animal_photo', ['id'], unique=False)
    op.create_index('ix__photo__animal_id', 'animal_photo', ['animal_id'], unique=False)
    op.drop_constraint(op.f('uq__animal__id'), 'animal', type_='unique')
    op.drop_column('animal', 'size')
    op.drop_column('animal', 'age')
    op.drop_column('animal', 'sex')
    op.drop_column('animal', 'type')
    # ### end Alembic commands ###
