"""add fk file

Revision ID: 619cced1d961
Revises: 
Create Date: 2023-12-23 12:29:51.933906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '619cced1d961'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name_ru', sa.String(), nullable=False),
                    sa.Column('name_en', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__animal')),
                    sa.UniqueConstraint('id', name=op.f('uq__animal__id'))
                    )
    op.create_table('animal_photo',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('animal_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk__photo__animal_id__animal'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__photo'))
                    )
    op.create_index(op.f('ix__photo__animal_id'), 'animal_photo', ['animal_id'], unique=False)
    op.create_index(op.f('ix__photo__id'), 'animal_photo', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__photo__id'), table_name='animal_photo')
    op.drop_index(op.f('ix__photo__animal_id'), table_name='animal_photo')
    op.drop_table('animal_photo')
    op.drop_table('animal')
    # ### end Alembic commands ###
