"""empty message

Revision ID: 7cc30087c9d7
Revises: 
Create Date: 2023-12-10 17:21:10.991388

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7cc30087c9d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name_ru', sa.String(), nullable=False),
                    sa.Column('name_en', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__animal')),
                    sa.UniqueConstraint('id', name=op.f('uq__animal__id'))
                    )
    op.create_table('photo',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('animal_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk__photo__animal_id__animal'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__photo'))
                    )
    op.create_index(op.f('ix__photo__animal_id'), 'photo', ['animal_id'], unique=False)
    op.create_index(op.f('ix__photo__id'), 'photo', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__photo__id'), table_name='photo')
    op.drop_index(op.f('ix__photo__animal_id'), table_name='photo')
    op.drop_table('photo')
    op.drop_table('animal')
    # ### end Alembic commands ###
