"""added_shelter_table

Revision ID: fdae3120f6f8
Revises: 3e3431180c42
Create Date: 2024-05-04 18:18:21.454167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdae3120f6f8'
down_revision: Union[str, None] = '3e3431180c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__shelter')),
    sa.UniqueConstraint('id', name=op.f('uq__shelter__id'))
    )
    op.add_column('animal', sa.Column('shelter_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix__animal__shelter_id'), 'animal', ['shelter_id'], unique=False)
    op.create_foreign_key(op.f('fk__animal__shelter_id__shelter'), 'animal', 'shelter', ['shelter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__animal__shelter_id__shelter'), 'animal', type_='foreignkey')
    op.drop_index(op.f('ix__animal__shelter_id'), table_name='animal')
    op.drop_column('animal', 'shelter_id')
    op.drop_table('shelter')
    # ### end Alembic commands ###
